version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: my_telegram_bot_db
      POSTGRES_USER: my_bot_user
      POSTGRES_PASSWORD: secure_password
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    depends_on:
      - db
    environment:
      POSTGRES_DB: my_telegram_bot_db
      POSTGRES_USER: my_bot_user
      POSTGRES_PASSWORD: secure_password
      POSTGRES_HOST: db
    ports:
      - "80:80"
    command: ["python", "-m", "my_telegram_bot.bot"]

volumes:
  pgdata:
