version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: my_telegram_bot_db
      POSTGRES_USER: my_bot_user
      POSTGRES_PASSWORD: secure_password
    volumes:
      - pgdata